### ISSUE TITLE
rabbitmq.config is set but not used?

### ISSUE THREAD

**Issue by petercv49** [gmr/pgsql-listen-exchange#13]
Windows environment with RabbitMQ 3.5.0, Erlang 17.4
Trying to use the rabbitmq.config file to set the db connection values.  Rabbitmq shows that the config file is found, but when I try to create an exchange, an econnrefused error occurs.  If I set the same values in the args of the exchange or in a policy, the exchange is created and messages appear when notify is used in the database.

**Comment by petercv49** [comment]
Reading through some of the other issues, I have upgraded by environment with RabbitMQ 3.5.4, Erlang 17.5, but still getting an error.
Here is my config file:
[
  {pgsql_listen_exchange,
    [
	  {host, "127.0.0.1"},
	  {port, 5432},
	  {dbname, "dev_database"},
	  {user, "dev_username"},
	  {password, "dev_password"}
	]}
].
Here is the error:
Got response code 500 with body {"error":"Internal Server Error","reason":"{error,\n {exit,\n {{{econnrefused,\n {gen_server,call,\n [pgsql_listen_worker,\n {validate,\n {exchange,\n {resource,<<\"/\">>,exchange,<<\"pgsql_exchange\">>},\n 'x-pgsql-listen',true,false,false,[],undefined,\n undefined,\n {[],[]}}}]}},\n [{gen_server,call,2,[{file,\"gen_server.erl\"},{line,182}]},\n {pgsql_listen_exchange,gen_server_call,1,\n [{file,\"src/pgsql_listen_exchange.erl\"},{line,94}]},\n {rabbit_exchange,declare,6,[]},\n {rabbit_channel,handle_method,3,[]},\n {rabbit_channel,handle_cast,2,[]},\n {gen_server2,handle_msg,2,[]},\n {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]},\n {gen_server,call,\n [<0.450.0>,\n {call,\n {'exchange.declare',0,<<\"pgsql_exchange\">>,\n <<\"x-pgsql-listen\">>,false,true,false,false,false,[]},\n none,<0.324.0>},\n infinity]}},\n [{gen_server,call,3,[{file,\"gen_server.erl\"},{line,190}]},\n {rabbit_mgmt_util,'-amqp_request/5-fun-0-',4,[]},\n {rabbit_mgmt_util,with_channel,5,[]},\n {rabbit_mgmt_util,http_to_amqp,5,[]},\n {webmachine_resource,resource_call,3,[]},\n {webmachine_resource,do,3,[]},\n {webmachine_decision_core,resource_call,1,[]},\n {webmachine_decision_core,accept_helper,1,[]}]}}\n"}

**Comment by j16sdiz** [comment]
Same error here.

My rabbitmq.config
<pre># cat  /etc/rabbitmq/rabbitmq.config
[{pgsql_listen_exchange,
  [
    {host, "127.0.0.1"},
    {port, 5432},
    {dbname, "keeblue"},
    {user, "rabbitmq"},
    {password, "XXX"}
  ]}
].
</pre>

postgresql log
<pre>
2015-10-26 10:34:23 HKT [32015-1] postgres@postgres FATAL:  password authentication failed for user "postgres"
2015-10-26 10:34:23 HKT [32015-2] postgres@postgres DETAIL:  User "postgres" has no password assigned.
        Connection matched pg_hba.conf line 86: "host    all             all             127.0.0.1/32            md5"
</pre>

I can confirm the correct config file is in effect:
<pre>
=INFO REPORT==== 26-Oct-2015::10:34:15 ===
node           : rabbit@fish
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : 16q6rEwhxccsRLe281Jm8g==
log            : /var/log/rabbitmq/rabbit@fish.log
sasl log       : /var/log/rabbitmq/rabbit@fish-sasl.log
database dir   : /var/lib/rabbitmq/mnesia/rabbit@fish
</pre>

**Comment by gmr** [comment]
Thanks for reporting, 1.0a1 - sorry it took nearly 5 years to fix.
