### ISSUE TITLE
Worker Supervisor Behavior is wrong

### ISSUE THREAD

**Issue by gmr** [gmr/pgsql-listen-exchange#17]
Fix the worker process supervisor behavior to properly work with queues and not start up on nodes if it's already running in the cluster

**Comment by bclune** [comment]
I'm interested in resolving this; would it be possible to use the `mirrored_supervisor` pattern from `rabbitmq-management` to provide cluster support, or are there challenges with that approach?

**Comment by gmr** [comment]
It is on my to-do list and will use mirred_supervisor in the same way as the management plugin. I've worked through the structure to get this working in a different WIP plugin and I'm working on: https://github.com/gmr/rabbitmq-pagerduty if you're curious.

**Comment by bclune** [comment]
Awesome, thanks for the link. Let me know if you need help testing when the changes hit this repo!

**Comment by gmr** [comment]
Addressed 4 years later in 1.0a1 :(
