### ISSUE TITLE
Compile for 3.6.x RabbitMQ

### ISSUE THREAD

**Issue by xolvo** [gmr/pgsql-listen-exchange#18]
Please, update this plugin to support new version of RabbitMQ.

**Comment by shadyvd** [comment]
And for 3.7+ now... Any plans of making a new release that supports the latest versions of RabbitMQ?

**Comment by gmr** [comment]
Not dead, just resting. Pining for the fjords, etc.

Probably very late for your use case, but 1.0a1 will drop soon with 3.8 support.
