### ISSUE TITLE
How to connect PostgreSQL and RabbitMQ

### ISSUE THREAD

**Issue by orionla2** [gmr/pgsql-listen-exchange#21]
Hello guys,

PostgreSQL 9.6.1
RabbitMQ 3.6.6

I am new with rabbitmq and need your help. I am trying connect my rabbitMQ container and postgreSQL container.

Could you please explain how should I configure my rabbitMQ container if PostgreSQL container configured as:
```
host: postgresql
port: 5432
dbname: postgres
dbuser: postgres
dbpassword: 123456789
```

I've tried add the 
```
{pgsql_listen_exchange,
[
    {host, "postgresql"},
    {port, 5432},
    {dbname, "postgres"},
    {user, "postgres"},
    {password, "123456789"}
]}
```
 to my rabbitmq.config file in the rabbitMQ container and sent from the PostgreSQL container 
```
NOTIFY test, 'Test message';
```

If I understand right than my listener should listen exchange named as x-pgsql-listen with keybind 'test' in any case here is my listener code:

```
<?php
require_once __DIR__ . '/../../../vendor/autoload.php';
use PhpAmqpLib\Connection\AMQPStreamConnection;
$connection = new AMQPStreamConnection('rabbitmq', 5432, 'admin', '123456789');
$channel = $connection->channel();
$channel->exchange_declare('x-pgsql-listen', 'topic', false, false, false);
list($queue_name, ,) = $channel->queue_declare("something", false, false, true, false);
$binding_keys = array_slice($argv, 1);
$channel->queue_bind($queue_name, 'x-pgsql-listen', 'test');
echo ' [*] Waiting for logs. To exit press CTRL+C', "\n";
$callback = function($msg){
  echo ' [x] ',$msg->delivery_info['routing_key'], ':', $msg->body, "\n";
};
$channel->basic_consume($queue_name, '', false, true, false, false, $callback);
while(count($channel->callbacks)) {
    $channel->wait();
}
$channel->close();
$connection->close();
?>
```

But nothing got in console log.

The question is how should I configure my RabbitMQ container according to my PostgreSQL container configurations via configuration file or via policy configurations?

**Comment by Yurist-85** [comment]
Did you enabled this plugin?
`rabbitmq-plugins enable pgsql_listen_exchange`

**Comment by orionla2** [comment]
Yes I did, I enabled plugin when I built the image with rabbitMQ. Also I double checked it and enabled inside the container again.

**Comment by gmr** [comment]
I think this was likely related to #13. Sorry for not addressing in a timely manner.
