### ISSUE TITLE
Error on enable plugin

### ISSUE THREAD

**Issue by BZR4** [gmr/pgsql-listen-exchange#23]
Hello. When trying to enable the plugin these errors occurred
{:plugins_not_found, [:pgsql_listen_exchange]}.
I'm using rabbitmq: management 3. docker. I copied the unzipped files to / opt / rabbitmq / plugins and the command rabbitmq-plugins enable pgsql_listen_exchange fails.

Could anyone help?

**Comment by gmr** [comment]
What version of RabbitMQ?
