### ISSUE TITLE
Handling of timestamps.

### ISSUE THREAD

**Issue by pnunn** [gmr/pgsql-listen-exchange#26]
Hi there.  I'm wondering if you can tell me what happens to timestamps as far as timezones go.

It seems that the data coming into my database as timestamp - no timezone, is hitting the rabbit queue as timestamp in UTC.

Is that correct?

Can that be changed, or do I need to assume this and handle the TZ change when I pull the data from the queue?

Thanks heaps.

Peter.

**Comment by pnunn** [comment]
Just thinking about this... is it because rabbit and the other VM's are probably running UTC?

**Comment by gmr** [comment]
We get the timestamp from the server time RabbitMQ is running on, specifically using `erlang:system_time`. See https://erlang.org/doc/apps/erts/time_correction.html#Erlang_System_Time

AFAIK the time is not conveyed by the database in the NOTIFY.

FWIW I would not use the `timestamp` as part of an application behavior contract, but instead as informative for debugging or understanding your message flow. If you need a contract for that behavior, I'd use ISO-Formatting timestamp values in your payload.

**Comment by pnunn** [comment]
Thanks Gavin.

What seems to be happening is the database has many timestamp fields for various parts of the tables.  (intervaltime, runtimedate, etc). In the DB they are timestamp no tz fields and the times are stored as Australian Eastern Standard time in YYYY-MM-DD HH:SS format (all of this is from the supplied schema etc and unfortunately can't be changed).

What I'm seeing in rabbit when I'm pulling out the messages (and I've only just now worked this out unfortunately :( , show's how well I checked things)...  that these fields are getting converted to UTC by the looks of things. I've got to confirm this with some simpler tests, but that is what it looks like.

I am using timestamp for logging as well, and that is in UTC on the containers running the GO code, and I wasn't sure if rabbit or go were doing the TZ conversion, but I can see the times are changed in the rabbit management console, so it seems to be there.

I'm not sure if I should leave them as UTC in the rabbit setup, and convert them in the go code, or try and fix them on the rabbit side... sigh.

**Comment by gmr** [comment]
If you're asking for an opinion here, I think you should stick with UTC on your servers and have your clients know that is the contract, and convert to the correct value for a local timezone as part of processing.

**Comment by gmr** [comment]
so timestamp in fields are a different issue.  Client timezone is a setting in the client session in Postgres and can be adjusted there. Conceptually we could allow for you to set this as part of the configuration for the exchange.

As a side note, if you do no have timezones anywhere, I find having an implicit contract of UTC everywhere is the most ideal thing.

Just for clarification, my first response was regard to the AMQP header `timestamp` and the behavior there.

**Comment by pnunn** [comment]
Yep.. thanks Gavin. Unfortunately the contract in this case is all defined by others :). I'll sort it out on my middleware I think.

Thanks for the input. Greatly appreciated.

**Comment by pnunn** [comment]
Hi Gavin, sorry for opening this again, but I've been looking at this most of the day and its actually not as easy as I'd hoped.

To handle the time zone changes in my consumer, I'd have to have a different consumer for each queue (there are about 8 of them). Not impossible, but a pain given if I can get the time fields in the correct timezone direct from rabbit, then I only need 8 instances of the same code, all just pulling different queues if that makes sense.

I tried changing the timezone of the rabbitmq-management container and got that working, but unfortunately the messages in the queues are still in UTC.

When I query the database from pgAdmin etc, the time fields are fine, so I guess that is the system converting them for me some how (the times are not the same as my workstation timezone either, so the time I put in seems to stick).

Is there any way to prevent the times being converted?  Is it being done by the query or the trigger? Do you happen to know?

Thanks.
Peter.
